// Generated by zkgroup/codegen/codegen.py - do not edit
package org.signal.zkgroup.profiles;

import org.signal.zkgroup.InvalidInputException;
import org.signal.zkgroup.ZkGroupError;
import org.signal.zkgroup.internal.ByteArray;
import org.signal.zkgroup.internal.Native;

public final class ProfileKeyCredentialRequestContext extends ByteArray {

  public static final int SIZE = 360;

  public ProfileKeyCredentialRequestContext(byte[] contents) throws InvalidInputException {
    super(contents, SIZE);
    
    int ffi_return = Native.profileKeyCredentialRequestContextCheckValidContentsJNI(contents);

    if (ffi_return == Native.FFI_RETURN_INPUT_ERROR) {
      throw new InvalidInputException("FFI_RETURN_INPUT_ERROR");
    }

    if (ffi_return != Native.FFI_RETURN_OK) {
      throw new ZkGroupError("FFI_RETURN!=OK");
    }
  }

  public ProfileKeyCredentialRequest getRequest() {
    byte[] newContents = new byte[ProfileKeyCredentialRequest.SIZE];

    int ffi_return = Native.profileKeyCredentialRequestContextGetRequestJNI(contents, newContents);

    if (ffi_return != Native.FFI_RETURN_OK) {
      throw new ZkGroupError("FFI_RETURN!=OK");
    }

    try {
      return new ProfileKeyCredentialRequest(newContents);
    } catch (InvalidInputException e) {
      throw new AssertionError(e);
    }

  }

  public byte[] serialize() {
    return contents.clone();
  }

}
