name: Release artifacts
on:
  push:
    tags:
      - v*

jobs:
  build_linux_android:
    name: Build Linux + Android
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com

      - name: Install pre-requisites
        run: |
          cargo install --version=1.0.0 cargo-ndk
          rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android

      - name: Build Android
        run: |
          cargo ndk --target aarch64-linux-android --platform 21 -- build --release
          cargo ndk --target armv7-linux-androideabi --platform 19 -- build --release
          cargo ndk --target i686-linux-android --platform 19 -- build --release
          cargo ndk --target x86_64-linux-android --platform 21 -- build --release
          find ./target -name libzkgroup.so | xargs zip libzkgroup-android.zip
        env:
          RUSTFLAGS: -C link-arg=-s
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk/
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk-bundle/

      - name: Read .nvmrc
        id: node_version
        working-directory: ffi/node
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node_version.outputs.NODE_VERSION }}'

      - name: Build Linux
        working-directory: ffi/node
        run: |
          npm --version
          node --version
          make libzkgroup

      - name: Upload Android
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libzkgroup-android.zip
          asset_name: libzkgroup-android.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload Linux
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup-x64.so
          asset_name: libzkgroup-x64.so
          tag: ${{ github.ref }}
          overwrite: true

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com

      - name: Read .nvmrc
        id: node_version
        working-directory: ffi/node
        run: echo "::set-output name=NODE_VERSION::$(cat .nvmrc)"

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node_version.outputs.NODE_VERSION }}'

      - name: Build
        working-directory: ffi/node
        run: |
          npm --version
          node --version
          make libzkgroup
      
      - name: Upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup-x64.dll
          asset_name: libzkgroup-x64.dll
          tag: ${{ github.ref }}
          overwrite: true

  build_macOS:
    name: Build macOS (Node)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com

      - name: Read .nvmrc
        id: node_version
        working-directory: ffi/node
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node_version.outputs.NODE_VERSION }}'

      - name: Build
        run: |
          npm --version
          node --version
          cd ffi/node
          make libzkgroup
      
      - name: Upload macOS
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup-x64.dylib
          asset_name: libzkgroup-x64.dylib
          tag: ${{ github.ref }}
          overwrite: true
