name: Code Formatting

on: [push]

jobs:

  code_formatting:
    name: Code Formatting
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run rustfmt
        run: |
          rustup component add rustfmt
          cargo fmt -- --check
